# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  workflow_dispatch:

name: install-test

jobs:
  install-test:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,  r: 'release'}
          - {os: ubuntu-20.04,   r: '4.3.2'}
          - {os: macOS-latest,   r: 'release'}
          - {os: macOS-11,       r: '4.3.2'}
          - {os: windows-latest, r: 'release'}
          - {os: windows-latest, r: '4.3.2'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_LIBS_USER: ${{ github.workspace }}/R

    steps:
      - uses: actions/checkout@v4

      - name: Install extra packages
        if: ${{ startsWith(matrix.config.os, 'ubuntu') }}
        run: |
          sudo apt-get update
          sudo apt-get -y install libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - name: Run tests
        run: |
          sink("test.out")
          update.packages(lib.loc=Sys.getenv("R_LIBS_USER"))
          source("https://kingaa.github.io/serrapilheira/prep/packages.R")
          source("https://kingaa.github.io/scripts/pompTest.R")
          source("https://kingaa.github.io/scripts/hello.R",echo=TRUE)
          source("https://kingaa.github.io/scripts/diagnostics.R",echo=TRUE)
          sink()
        shell: Rscript {0}
      
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.config.os }}-${{ matrix.config.r }}-results
          path: ${{ github.workspace }}/test.out
